nfl_next_gen_stats/urls.py
from . import views
from django.urls import include, path

urlpatterns = [
    # Regular Views
    path('', views.home, name='home'),
    path('player-search/', views.SearchResultsView.as_view(), name='player-search'),
    path('player/<str:gsis_id>/', views.player_page, name='player-page'),
    path('player/<str:gsis_id>/<int:season>/', views.player_page, name='player-season'),

    # API Views
    path('api/qb-ngs-stats/<int:season>/', views.qb_ngs_api, name='qb-api'),
    path('api/wr-ngs-stats/<int:season>/<int:week>/', views.wr_ngs_api, name='wr-api'),
]

ngs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('nfl_next_gen_stats.urls')),
    path('admin/', admin.site.urls),
]

nfl_next_gen_stats/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    full_name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=200)
    gsis_id = models.CharField(max_length=20, unique=True)
    team = models.CharField(max_length=20, blank=True, null=True)
    position = models.CharField(max_length=20, blank=True, null=True)

    def passing_stats(self):
        return PassingStats.objects.filter(gsis_id=self.gsis_id)

    def rushing_stats(self):
        return RushingStats.objects.filter(gsis_id=self.gsis_id)

    def receiving_stats(self):
        return ReceivingStats.objects.filter(gsis_id=self.gsis_id)

    def __str__(self):
        return f"{self.full_name} ({self.gsis_id})"


class PassingStats(models.Model):
    gsis = models.ForeignKey(Player, to_field='gsis_id', on_delete=models.CASCADE)
    season = models.IntegerField()
    season_type = models.CharField(max_length=50)
    week = models.IntegerField()
    position = models.CharField(max_length=10)
    team = models.CharField(max_length=10)
    avg_time_to_throw = models.FloatField(blank=True, null=True)
    avg_completed_air_yards = models.FloatField(blank=True, null=True)
    avg_intended_air_yards = models.FloatField(blank=True, null=True)
    avg_air_yards_differential = models.FloatField(blank=True, null=True)
    aggressiveness = models.FloatField(blank=True, null=True)
    max_completed_air_distance = models.FloatField(blank=True, null=True)
    avg_air_yards_to_sticks = models.FloatField(blank=True, null=True)
    attempts = models.IntegerField(blank=True, null=True)
    pass_yards = models.IntegerField(blank=True, null=True)
    pass_touchdowns = models.IntegerField(blank=True, null=True)
    interceptions = models.IntegerField(blank=True, null=True)
    passer_rating = models.FloatField(blank=True, null=True)
    completions = models.IntegerField(blank=True, null=True)
    completion_percentage = models.FloatField(blank=True, null=True)
    expected_completion_percentage = models.FloatField(blank=True, null=True)
    completion_percentage_above_expectation = models.FloatField(blank=True, null=True)
    avg_air_distance = models.FloatField(blank=True, null=True)
    max_air_distance = models.FloatField(blank=True, null=True)
    player_jersey_number = models.IntegerField(blank=True, null=True)

class RushingStats(models.Model):
    gsis = models.ForeignKey(Player, to_field='gsis_id', on_delete=models.CASCADE)
    season = models.IntegerField()
    season_type = models.CharField(max_length=50)
    week = models.IntegerField()
    position = models.CharField(max_length=10)
    team = models.CharField(max_length=10)
    efficiency = models.FloatField(blank=True, null=True)
    percent_attempts_gte_eight_defenders = models.FloatField(blank=True, null=True)
    avg_time_to_los = models.FloatField(blank=True, null=True)
    rush_attempts = models.IntegerField(blank=True, null=True)
    rush_yards = models.IntegerField(blank=True, null=True)
    expected_rush_yards = models.FloatField(blank=True, null=True)
    rush_yards_over_expected = models.FloatField(blank=True, null=True)
    avg_rush_yards = models.FloatField(blank=True, null=True)
    rush_yards_over_expected_per_att = models.FloatField(blank=True, null=True)
    rush_pct_over_expected = models.FloatField(blank=True, null=True)
    rush_touchdowns = models.IntegerField(blank=True, null=True)
    player_jersey_number = models.IntegerField(blank=True, null=True)

class ReceivingStats(models.Model):
    gsis = models.ForeignKey(Player, to_field='gsis_id', on_delete=models.CASCADE)
    season = models.IntegerField()
    season_type = models.CharField(max_length=50)
    week = models.IntegerField()
    position = models.CharField(max_length=10)
    team = models.CharField(max_length=10)
    player_jersey_number = models.IntegerField(blank=True, null=True)
    avg_cushion = models.FloatField(blank=True, null=True)
    avg_separation = models.FloatField(blank=True, null=True)
    avg_intended_air_yards = models.FloatField(blank=True, null=True)
    percent_share_of_intended_air_yards = models.FloatField(blank=True, null=True)
    receptions = models.IntegerField(blank=True, null=True)
    targets = models.IntegerField(blank=True, null=True)
    catch_percentage = models.FloatField(blank=True, null=True)
    yards = models.IntegerField(blank=True, null=True)
    rec_touchdowns = models.IntegerField(blank=True, null=True)
    avg_yac = models.FloatField(blank=True, null=True)
    avg_expected_yac = models.FloatField(blank=True, null=True)
    avg_yac_above_expectation = models.FloatField(blank=True, null=True)

nfl_next_gen_stats/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from .models import *
import numpy as np


def home(request):
    return render(request, 'nfl_next_gen_stats/home.html')


class SearchResultsView(ListView):
    model = Player
    template_name = 'nfl_next_gen_stats/player-search.html'

    def get_queryset(self):
        query = self.request.GET.get('player')
        if query:
            object_list = Player.objects.filter(Q(full_name__icontains=query))
            return object_list
        else:
            return None


def qb_ngs_api(request, season=None):
    passing_queryset = PassingStats.objects.filter(week=0, season=season).values()

    final = []
    for p in passing_queryset:
        final.append({
            'player': Player.objects.get(gsis_id=p.get('gsis_id')).full_name,
            'stats': p
        })

    return JsonResponse(final, safe=False)


def wr_ngs_api(request, season=None, week=0):
    receiving_queryset = ReceivingStats.objects.filter(week=week, season=season).values()

    final = []
    for p in receiving_queryset:
        final.append({
            'player': Player.objects.get(gsis_id=p.get('gsis_id')).full_name,
            'stats': p
        })

    return JsonResponse(final, safe=False)


def player_page(request, gsis_id=None, season=None):

    player = get_object_or_404(Player, gsis_id=gsis_id)
    passing_stats = player.passing_stats().order_by('season', 'week')
    rushing_stats = player.rushing_stats().order_by('season', 'week')
    receiving_stats = player.receiving_stats().order_by('season', 'week')

    pass_years = np.array(passing_stats.order_by('season').values_list('season', flat=True).distinct())
    rush_years = np.array(rushing_stats.order_by('season').values_list('season', flat=True).distinct())
    rec_years = np.array(receiving_stats.order_by('season').values_list('season', flat=True).distinct())

    years = np.append(pass_years, rush_years)
    years = np.append(years, rec_years)

    context = {
        'player': player,
        'years': years
    }

    if season:
        context.update({
            'title': f"{player.full_name} -- {season}",
            'season': season,
            'passing_stats': passing_stats.filter(~Q(week=0), season=season),
            'rushing_stats': rushing_stats.filter(~Q(week=0), season=season),
            'receiving_stats': receiving_stats.filter(~Q(week=0), season=season),
        })

    else:
        context.update({
            'title': player.full_name,
            'passing_stats': passing_stats.filter(week=0),
            'rushing_stats': rushing_stats.filter(week=0),
            'receiving_stats': receiving_stats.filter(week=0),
        })

    return render(request, 'nfl_next_gen_stats/player.html', context)

nfl_next_gen_stats/templates/nfl_next_gen_stats/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link 
            rel="stylesheet" 
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
            crossorigin="anonymous"
        >

        <!-- Static CSS -->
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'nfl_next_gen_stats/main.css' %}"> -->

        <title>{{ title }}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <a class="navbar-brand" href="#">NGS Viewer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'player-search' %}">Player Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://nextgenstats.nfl.com/glossary" target="_blank">Glossary (NFL.com)</a>
                    </li> 
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            {% block content %}{% endblock %}
        </main>
    </body>
</html>

nfl_next_gen_stats/templates/nfl_next_gen_stats/home.html
{% extends 'nfl_next_gen_stats/base.html' %}
{% block content %}
    <h1>Welcome!</h1>
{% endblock content %}

nfl_next_gen_stats/templates/nfl_next_gen_stats/player-search.html
{% extends 'nfl_next_gen_stats/base.html' %}
{% block content %}
    <h1>NGS Player Searson</h1>
    <div>
        <p>Use the search bar below to search for a player by name. You can type in any part of a players name and then hit the submit button.</p>
    </div>
    <form action="{% url 'player-search' %}" method="get">
        <input name="player" type="text" placeholder="Search for a player">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Results</h3>
    <div class="player-results">
        <ul>
            {% for player in player_list %}
                <li><a href="{% url 'player-page' player.gsis_id %}">{{ player.full_name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

nfl_next_gen_stats/templates/nfl_next_gen_stats/player.html
{% extends 'nfl_next_gen_stats/base.html' %}
{% block content %}
    <div class="player-stats-header">
        {% if season %}
            <h1>{{ player.full_name }}'s {{ season }} NGS Stats</h1>
            <p><a href="{% url 'player-page' player.gsis_id %}">Visit Career Stats</a></p>
        {% else %}
            <h1>{{ player.full_name }}'s Career NGS Stats</h1>
        {% endif %}
        <span style="display: block;"><strong>Team: </strong>{{ player.team }}</span>
        <span style="display: block;"><strong>Position: </strong>{{ player.position }}</span>
        <span style="display: block;"><strong>Years: </strong>
            {% for year in years %}
                <a href="{% url 'player-season' player.gsis_id year|floatformat:0 %}">{{ year|floatformat:0 }}</a>
            {% endfor %}
        </span>
    </div>
    <div class="player-stats-main">
        <div class="player-stats-passing">
            <h2>Passing Stats</h2>
            <!-- TODO: TURN INTO FLEXBOX -->
            <table class="table table-sm">
                <thead class="text-center bg-info text-white">
                    <tr>
                        <th>Year</th>
                        {% if season %}
                            <th>Week</th>
                        {% endif %}
                        <th>Pos</th>
                        <th>Team</th>
                        <th>Number</th>
                        <th title="Average Time To Throw">ATTT</th>
                        <th title="Average Completed Air Yards">ACAY</th>
                        <th title="Average Intended Air Yards">AIAY</th>
                        <th title="Average Air Yards Differential">AAYD</th>
                        <th title="Aggressiveness">AGG</th>
                        <th title="Average Air Distance">AAD</th>
                        <th title="Max Air Distance">MAD</th>
                        <th title="Max Completed Air Distance">MCAD</th>
                        <th title="Average Air Yards To Sticks">AAYTS</th>
                        <th title="Passer Rating">RAT</th>
                        <th title="Attempts">ATT</th>
                        <th title="Completions">COMP</th>
                        <th title="Completion Percentage">COMP%</td>
                        <th title="Expected Completion Percentage">xCOMP%</td>
                        <th title="Completion Percentage Above Expectation">+/-</th>
                        <th title="Passing Yards">Yards</th>
                        <th title="Interceptions">INT</th>
                        <th title="Passing Touchdowns">TD</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for stat in passing_stats %}
                        <tr>
                            <td>
                                {% if season %}
                                    {{ stat.season }}
                                {% else %}
                                    <a href="{% url 'player-season' player.gsis_id stat.season %}">
                                        {{ stat.season }}
                                    </a>
                                {% endif %}
                            </td>
                            {% if season %}
                                <td>{{ stat.week }}</td>
                            {% endif %}
                            <td>{{ stat.position }}</td>
                            <td>{{ stat.team }}</td>
                            <td>{{ stat.player_jersey_number }}</td>
                            <td>{{ stat.avg_time_to_throw|floatformat:2 }}</td>
                            <td>{{ stat.avg_completed_air_yards|floatformat:2 }}</td>
                            <td>{{ stat.avg_intended_air_yards|floatformat:2 }}</td>
                            <td>{{ stat.avg_air_yards_differential|floatformat:2 }}</td>
                            <td>{{ stat.aggressiveness|floatformat:2 }}</td>
                            <td>{{ stat.avg_air_distance|floatformat:2 }}</td>
                            <td>{{ stat.max_air_distance|floatformat:2 }}</td>
                            <td>{{ stat.max_completed_air_distance|floatformat:2 }}</td>
                            <td>{{ stat.avg_air_yards_to_sticks|floatformat:2 }}</td>
                            <td>{{ stat.passer_rating|floatformat:2 }}</td>
                            <td>{{ stat.attempts }}</td>
                            <td>{{ stat.completions }}</td>
                            <td>{{ stat.completion_percentage|floatformat:2 }}%</td>
                            <td>{{ stat.expected_completion_percentage|floatformat:2 }}%</td>
                            <td>{{ stat.completion_percentage_above_expectation|floatformat:2 }}%</td>
                            <td>{{ stat.pass_yards }}</td>
                            <td>{{ stat.interceptions }}</td>
                            <td>{{ stat.pass_touchdowns }}</td>
                        </tr>
                    {% empty %}
                        <th>
                            <td colspan="25">There are no passing stats for {{ player.full_name }}</td>
                        </th>
                    {% endfor %}
                </tbody>
            </table>
        
            <p>Note: NGS webpage only shows players with a minumum passing attempts for that week/season. Please see the NGS website for more details.</p>
        </div>

        <div class="player-stats-rushing">
            <h2>Rushing Stats</h2>
            <!-- TODO: TURN INTO FLEXBOX -->
            <table class="table table-sm">
                <thead class="text-center bg-info text-white">
                    <tr>
                        <th>Year</th>
                        {% if season %}
                            <th>Week</th>
                        {% endif %}
                        <th>Pos</th>
                        <th>Team</th>
                        <th>Number</th>
                        <th title="Efficiency">EFF</th>
                        <th title="8+ Defenders In The Box">8+D%</th>
                        <th title="Average Time Behind Line of Scrimmage">TLOS</th>
                        <th title="Rushing Attempts">ATT</th>
                        <th title="Rushing Yards">Yards</th>
                        <th title="Rushing Touchdowns">TD</th>
                        <th title="Expected Rushing Yards">xYards</th>
                        <th title="Rushing Yards Over Expected">RYOE</th>
                        <th title="Average Rushing Yards">AVG</th>
                        <th title="Rushing Yards Over Expected Per Attempt">RYOE/ATT</th>
                        <th title="Rushing Percentage Over Expected">RPOE</td>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for stat in rushing_stats %}
                        <tr>
                            <td>
                                {% if season %}
                                    {{ stat.season }}
                                {% else %}
                                    <a href="{% url 'player-season' player.gsis_id stat.season %}">
                                        {{ stat.season }}
                                    </a>
                                {% endif %}
                            </td>
                            {% if season %}
                                <td>{{ stat.week }}</td>
                            {% endif %}
                            <td>{{ stat.position }}</td>
                            <td>{{ stat.team }}</td>
                            <td>{{ stat.player_jersey_number }}</td>
                            <td>{{ stat.efficiency|floatformat:2 }}</td>
                            <td>{{ stat.percent_attempts_gte_eight_defenders|floatformat:2 }}%</td>
                            <td>{{ stat.avg_time_to_los|floatformat:2 }}</td>
                            <td>{{ stat.rush_attempts }}</td>
                            <td>{{ stat.rush_yards }}</td>
                            <td>{{ stat.rush_touchdowns }}</td>
                            <td>{{ stat.expected_rush_yards|floatformat:2 }}</td>
                            <td>{{ stat.rush_yards_over_expected|floatformat:2 }}</td>
                            <td>{{ stat.avg_rush_yards|floatformat:2 }}</td>
                            <td>{{ stat.rush_yards_over_expected_per_att|floatformat:2 }}</td>
                            <td>{% widthratio stat.rush_pct_over_expected 1 100 %}%</td>
                        </tr>
                    {% empty %}
                        <th>
                            <td colspan="20">There are no rushing stats for {{ player.full_name }}</td>
                        </th>
                    {% endfor %}
                </tbody>
            </table>
        
            <p>Note: NGS webpage only shows players with a minumum rushing attempts for that week/season. Please see the NGS website for more details.</p>
        </div>

        <div class="player-stats-receiving">
            <h2>Receiving Stats</h2>
            <!-- TODO: TURN INTO FLEXBOX -->
            <table class="table table-sm">
                <thead class="text-center bg-info text-white">
                    <tr>
                        <th>Year</th>
                        {% if season %}
                            <th>Week</th>
                        {% endif %}
                        <th>Pos</th>
                        <th>Team</th>
                        <th>Number</th>
                        <th title="Average Cushion">CUSH</th>
                        <th title="Average Separation">SEP</th>
                        <th title="Average Intended Air Yards">IAY</th>
                        <th title="Percent of Intended Air Yards">IAY%</th>
                        <th title="Receptions">REC</th>
                        <th title="Targets">TAR</th>
                        <th title="Catch Percentage">CATCH%</th>
                        <th title="Yards">Yards</th>
                        <th title="Receiving Touchdowns">TD</th>
                        <th title="Average YAC">YAC/R</th>
                        <th title="Average xYAX">xYAX/R</th>
                        <th title="Average YAC Above Expectation">+/-</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for stat in receiving_stats %}
                        <tr>
                            <td>
                                {% if season %}
                                    {{ stat.season }}
                                {% else %}
                                    <a href="{% url 'player-season' player.gsis_id stat.season %}">
                                        {{ stat.season }}
                                    </a>
                                {% endif %}
                            </td>
                            {% if season %}
                                <td>{{ stat.week }}</td>
                            {% endif %}
                            <td>{{ stat.position }}</td>
                            <td>{{ stat.team }}</td>
                            <td>{{ stat.player_jersey_number }}</td>
                            <td>{{ stat.avg_cushion|floatformat:2 }}</td>
                            <td>{{ stat.avg_separation|floatformat:2 }}</td>
                            <td>{{ stat.avg_intended_air_yards|floatformat:2 }}</td>
                            <td>{{ stat.percent_share_of_intended_air_yards|floatformat:2 }}%</td>
                            <td>{{ stat.receptions }}</td>
                            <td>{{ stat.targets }}</td>
                            <td>{{ stat.catch_percentage|floatformat:2 }}%</td>
                            <td>{{ stat.yards }}</td>
                            <td>{{ stat.rec_touchdowns }}</td>
                            <td>{{ stat.avg_yac|floatformat:2 }}</td>
                            <td>{{ stat.avg_expected_yac|floatformat:2 }}</td>
                            <td>{{ stat.avg_yac_above_expectation|floatformat:2 }}</td>
                        </tr>
                    {% empty %}
                        <th>
                            <td colspan="20">There are no reciving stats for {{ player.full_name }}</td>
                        </th>
                    {% endfor %}
                </tbody>
            </table>
        
            <p>Note: NGS webpage only shows players with a minumum targets for that week/season. Please see the NGS website for more details.</p>
        </div>
    </div>
{% endblock content %}